### ISSUE TITLE
Can we have generated and editable files in different folders?

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium-regtest#2]
Currently there are 165 files in nno-nob/test for 6 testsets. If I want to add inputs/golds, that's quite a lot of file names for my human eyes to parse. Would it be possible to have something like

```
/test/humaneditable.input.txt
/test/humaneditable.gold.txt
/test/generated/pendingtaggeroutputexpected.txt
```

?

(In my quickly-hacked-together regtest approximation in nno-nob/tests I do this, with 20 different test sets)

**Comment by TinoDidriksen** [comment]
That makes sense.

I'd say go even further, keeping input files in `test/` directly, and then having `test/expected/` `test/gold/` `test/output/` all separated. Because there can be a gold file for each step in the pipe, they would likewise flood the main folder.

And having `output/` separate and not versioned makes it very easy to `.gitignore` and `clean`

**Comment by mr-martian** [comment]
With the current setup, `tests.json` can specify an arbitrary (relative) path for the input, so those at least could be put in a different folder.

Having subfolders rather than different filenames does seem like a much better system and I wish I had thought of it before setting it up in 365 places.

I suppose there could be a setting in `tests.json` to specify the directory structure.

**Comment by mr-martian** [comment]
Done, and the `tools/flat2nest.py` script will automate the transition.
